module.exports = [
	// USERS table
	`CREATE TABLE IF NOT EXISTS USERS
	(
		USER_ID INT NOT NULL AUTO_INCREMENT,
		FIRST_NAME VARCHAR(20) NOT NULL,
		LAST_NAME VARCHAR(20) NOT NULL,
		EMAIL VARCHAR(30) NOT NULL UNIQUE,
		PASSWORD VARCHAR(256) NOT NULL,
		CONSTRAINT USERS_PK PRIMARY KEY (USER_ID)
	)AUTO_INCREMENT = 2000;`,

	// USER_AUTH table
	`CREATE TABLE IF NOT EXISTS USER_AUTH
	(
		AUTH_ID INT AUTO_INCREMENT,
		USER_ID INT NOT NULL,
		JWT_TOKEN VARCHAR(256) NOT NULL,
		CONSTRAINT USER_AUTH_PK PRIMARY KEY(AUTH_ID),
		FOREIGN KEY(USER_ID) REFERENCES USERS(USER_ID)
		ON UPDATE CASCADE ON DELETE CASCADE
	);`,

	// EVENTS table
	`CREATE TABLE IF NOT EXISTS EVENTS
	(
		NAME VARCHAR(20) NOT NULL,
		YEAR YEAR NOT NULL,
		IMG_URL VARCHAR(256) NOT NULL,
		DESCRIPTION VARCHAR(100) NOT NULL,
		LINK VARCHAR(500) NOT NULL,
		PRIMARY KEY (name)
	);`
]